### ISSUE TITLE
Non standalone builds should mark include files as SYSTEM

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#28]
The binlog CMake target_include_directories call should detect when binlog is being compiled as part of another project and mark the include files as SYSTEM so that extra compiler warnings enabled by the parent project can't be triggered on the binlog header files.

Reasoning: The current convention in binlog of having constructor parameters named the same as private class members is causing compiler warnings for users who have -Wshadow enabled and breaking users who have both -Wshadow and -Werror enabled.

Example Fix: https://github.com/microsoft/GSL/blob/master/CMakeLists.txt#L58

**Comment by erenon** [comment]
Thanks for reporting. I also filed https://github.com/Morgan-Stanley/binlog/issues/29 - to get rid of `-Wshadow` errors.

**Comment by erenon** [comment]
@andrewkcorcoran : Please review https://github.com/Morgan-Stanley/binlog/pull/34  - Thanks.
