### ISSUE TITLE
Allow log rotation

### ISSUE THREAD

**Issue by erenon** [Morgan-Stanley/binlog#3]
Log rotation is a popular feature, allowing long running apps to keep logging while discarding old logs.

`Session::consume(ostream&)` takes an arbitrary `ostream`, therefore allows the target to be rotated by simply changing the given argument. However, since the session does not know about the target file, it does not re-send the metadata: the rotated files can be converted only together, which does not allow the removal of old files.

Add a new API (e.g: `Session::rewindMetadata`) which makes the next `consume` to emit metadata again, allowing simple rotations by a change of the consume argument.

**Comment by jackyjia** [comment]
Thanks for opening this issue. when will be the first release and will log rotation be included? Thanks.

**Comment by erenon** [comment]
Now that the holiday season is over, log rotation will be the first addition. For now, the release model is rolling release - each commit is consistent, reviewed and fully tested. Later (esp. if there'll be packaging need), we'll have signed, tagged releases.

**Comment by jackyjia** [comment]
> Now that the holiday season is over, log rotation will be the first addition. For now, the release model is rolling release - each commit is consistent, reviewed and fully tested. Later (esp. if there'll be packaging need), we'll have signed, tagged releases.

Great. Thanks a lot and looking forward to the log rotation feature soon.

**Comment by erenon** [comment]
@jackyjia : Please see #9 and check if this is what you are looking for/something you can start working with/something else.
