### ISSUE TITLE
Add support for std::optional

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#42]
The below seems to be missing from mserialize and needs to be added manually by the user

```
namespace mserialize { namespace detail {
  template <typename T> struct is_optional<std::optional<T>> : std::true_type {};
}}
```

**Comment by erenon** [comment]
Correct, this is because `std::optional` is there since C++17, and binlog is purely C++14, to reduce testing burden (i.e: test each branch of preprocessor conditions). However, in the long run, new vocabulary types (optional, variant) and common types (filesystem::path) should be supported.

**Comment by andrewkcorcoran** [comment]
In the short term do you think adding an `include/binlog/binlogCpp17.hpp` would make sense? This wouldn't be included by `include/binlog/binlog.hpp` and therefore would maintain C++14 support in binlog but allow users who are on C++17 to opt in to C++17 features? Alternatively some nasty `#ifdefs` could be setup to try and detect the C++ std version. Doing that manually with bringing in boost config as dependency wouldn't be ideal through.

**Comment by erenon** [comment]
I'm thinking about adding `include/binlog/adapt_stdoptional.hpp`, that unconditionally includes `<optional>`, free to be included by C++17 clients and tests. The same could be done later for boost equivalents, if needed.

The only question is, whether `binlog.hpp` should include these, if `__cplusplus` indicates C++17 or greater.
