### ISSUE TITLE
Make bread able to sort the logstream by time

### ISSUE THREAD

**Issue by erenon** [Morgan-Stanley/binlog#6]
By default, `bread` prints log events in the log stream in order of appearance. Normally, this means the events of each thread are batched together, making cross-thread interaction more difficult to reason about.

Add a switch (`-s`) to `bread`, that makes it sort events in the stream by time. A simple implementation would be to read every event, then sort and print them in one go. However, this approach has a high time-to-first-event latency, high memory usage, and does not work with live streams.

A more involved approach would be to assume that events are sorted to a certain extent (e.g: events more than 60 seconds apart in the log will not be out of order), read a window of events sort and print some of the window, then repeat.

**Comment by loveyoupeng** [comment]
how about create predefined sized sections/blocks in the log file for each session, and a mark card as session index, then "merge sort" the result.

**Comment by erenon** [comment]
I'm not sure I understand your suggestion. One way to go about it is to define the window as a set of batches of unique writers (identified by writer id), and merge sort those batches. However, if a writer fills its queue, by default, it allocates a new one, which means the events of a single writer can span multiple batches, invalidating the assumption above.

**Comment by loveyoupeng** [comment]
instead of assigning one section to one session, how about using fix sized linked blocks, each block has pre-defined size, and once a session's block filled up, it is assigned a new block and "link" the two blocks together

**Comment by erenon** [comment]
Just to make sure we are on the same page: this ticket is about sorting a stream of log events in the `bread` program. Do you suggest to use a two pass algorithm? One pass to identify the event batches of each log writer in the whole stream, then in a second pass, merge sort them?
This could work for complete files, but not for streams, e.g: when reading a live logfile,or when the logfile is really huge.

**Comment by loveyoupeng** [comment]
I got your point here. you try to do the magic in bread, which is valid, my suggestion is based on log persistent "consume" call is done by NOT critical path resources, the operation could be a little bit "slower" which make it much easier for bread to sort the events out. 
what I suggested is collaborate the effort of generating log and bread log.
For a given log file A, we could consider it as 4k blocks, each time each block can only contain one writer's contents, each time of "consume" invocation, it will locate the last block of the write and pure the events, once a block is filled up, it get a new allocation and leave a link pointer.
at the very beginning, we could keep the meta data of the first and last block for each writer.
During the reading, the bread only needs to "merge" the blocks for each writer, and only keep one block each writer at most in memory.
Given reads has to done through bread, the file format could be open for complex design.

The other way is by registering all the writer to a "Sink", and only "consume" from the sink, during consume invocation, it could merge all the channels' content and write to the file.

**Comment by erenon** [comment]
I understand the proposition now. While this approach could make offline sorting easier, there are some important details. Currently, a binlog logfile is an append-only stream. Segmenting the logfile as suggested would change this to a random access file, that is difficult to implement, if the target is e.g: a pipe, a socket some agnostic middle layer (compression, encryption), etc. Also, cross batch pointers prevent (or make more difficult) injecting entries intto the stream later, and make log rotation more complex.
In the bread side, probably the two pass would be still necessary, to discover the start of each writer.

> Given reads has to done through bread, the file format could be open for complex design.

True, but I intend to keep the format as simple as possible, to make it easier to add different producers and consumers, e.g: a java writer, or a python reader for quick statistics or log analysis.

**Comment by loveyoupeng** [comment]
Cool, totally agree KISS is better than complex show off 😄 
You may bring up another design corner to handle, given the general "logger file contract" no matter if it is persistent to file or a pipe/socket, chronicle total order of all events may be assumed, which means existing down streams expecting the log events are in merged and sorted by timestamp.
in that case probably better to merge sort during "consume".

**Comment by erenon** [comment]
I don't see a reasonable way to merge sort in `Session::consume`. Assume the following (wrong) algorithm:

```
std::vector<ReadResult> buffers;
for (auto&& c : _channels) { buffers.push_back(c.reader.beginRead()); }
// ... then merge sort buffers in buffers
```

Assume C is the consumer thread, and there are two producer threads, T1 and T2.
Then the following sequence of events:

 - C fetches the buffer of T1 from its queue
 - T1 adds a new event to its queue
 - T2 adds a new event to its queue
 - C fetches the buffer of T2
 - C merge sorts the fetched buffers. This is wrong, as the last event of T2 will be sorted and consumed, but the last event of T1 will not be, despite it comes before (by timestamp) the last event of T2.

`Session::consume` can't use a sliding window trick as `bread` can, as it would unnecessarily increase the pressure on the queues.

**Comment by loveyoupeng** [comment]
Yes, I missed the race case, great catch.  :+1:   
However, there is a trick to deal it without pressure the log buffer, we could poll all the events from the buffer, and only merge sort all the events before the last event timestamp of the first polled buffer, and leave the rest in a temporary buffer for the consumer, and merge them with the next poll.

```c++
long timestamp;
bool first = false;
for(auto channel : channels) {
    channel.poll(buffer);
    if(first) {
        timetamp = lastTimestamp(buffer);
        first = true;
   }
  mergesort(buffer, timestamp);
  // write the result to file and leave all event in the buffer if timestamp > timestamp
}
```
