### ISSUE TITLE
bread ubsan error

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#62]
```binlog/include/binlog/Time.cpp:7:41: runtime error: signed integer overflow: 31534085395 * 1000000000 cannot be represented in type 'long int'```

**Comment by erenon** [comment]
Thanks for reporting, this seems serious. I'm working on it, but couldn't find a trivial, efficient fix yet.

**Comment by erenon** [comment]
Fixed by #63
