### ISSUE TITLE
Don't force build type on non standalone builds

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#67]
For standalone builds of binlog it's probably fine to force an unspecified CMAKE_BUILD_TYPE to be RelWithDebInfo. However setting this value in a non standalone build affects all other projects which are being built.

**Comment by erenon** [comment]
Does it matter when binlog is built as part of a source tree, via cmake include? Then it could be resolved by splitting the main CMakeLists.txt, as it also affects other settings (eg standard to be used) OR by making those settings conditional. Ill see which approach yields to simpler code.

**Comment by erenon** [comment]
@andrewkcorcoran see https://github.com/Morgan-Stanley/binlog/pull/69
