### ISSUE TITLE
support fixed size array, and struct copy

### ISSUE THREAD

**Issue by fdrex** [Morgan-Stanley/binlog#68]
To further improve the performance, it's better to support fixed size array - std::array<T, N>, char [N]. You can embed the size of the array in the tag, so in most cases, a simple memcpy will be enough for serialization just like primitive types do.

suggested tag: 
```
<FixedSizeArrayTag> := # `SizeInHex' <ElementTypeTag>
```

For simple POD struct (which may contain char[N] as fields), we'd also like to have a memcpy style tag. e.g.

```
<MemcpyStructTag> :=
={SizeInHex [`OffsetInHex' <FieldTypeTag>]*}
```

If the above two can be implemented, the serialization will be effectively optimized by the compiler to a fixed-size-memcpy in a lot of cases, thus push the performance to the limit.

**Comment by erenon** [comment]
Hi, thanks for thinking about this.
The mentioned optimization is already possible by assigning a tuple tag (i.e: a sequence of fixed number of objects) to e.g: `std::array`:

    tag(std::array<char, 8>) == "(cccccccc)"

I will take a look (much later, unless you can provide some measurements and generated code) if such a specialization for common sequence of PODs can help performance in a measurable way.

**Comment by fdrex** [comment]
Take your time. I'll post some measurements when we have.

**Comment by fdrex** [comment]
This project is quite interesting, and the quality is quite good. We find this when we are having basiclly the same idea. Nice job
