### ISSUE TITLE
Add crash recovery

### ISSUE THREAD

**Issue by erenon** [Morgan-Stanley/binlog#7]
Binlog does asynchronous logging, therefore if the application crashes, the most recent, probably most relevant logs, will still be in the queues, not flushed to the log output. However, if there's a coredump (minidump), nothing is lost, only the queue content must be recovered.

Create a program, `brecovery`, which takes a coredump (minidump, or any kind of memory image), and extracts unconsumed queue data. Usage:

    $ brecovery myapp.1234.core recovered_log.blog

Solution: Make Queue instances discoverable in the cordump, and link queue buffers to queue instances. Steps:

 - Add a const magic number to the Queue class (e.g: a random generated number)
 - Add a instance unique identifier to each queue object (i.e: the pointer of itself)
 - Verify by static_assert the offset of the important Queue fields
 - Allocate slightly larger buffer for each queue. In the beginning of the queue, add a different magic number, and a pointer to the queue.

Recovery process: scan the whole coredump, looking for the two magic numbers. Link found queues and buffers by the queue identifier. Read reader and writer positions from the queue, extract data from the linked buffer accordingly, write extracted data to the specified output.

Testing: on Linux, if available, gcore can be used to create corefiles out of test programs. On Windows, Userdump.exe, ProcDump, or MiniDumpWriteDump can be used.

**Comment by loveyoupeng** [comment]
not sure if mmap the queues to tmp file could do the trick, which gives the opportunities to consume the queues from different process

**Comment by erenon** [comment]
Putting the queue to shared memory and using an off-process consumer is definitely an option, but outside the current scope of the project, because of the platform specific nuances and additional complexity of managing multiple processes.

**Comment by loveyoupeng** [comment]
definitely understand your priorities, you guys have done a great work.
