### ISSUE TITLE
change const char* and char* tag to "optional of array"

### ISSUE THREAD

**Issue by fdrex** [Morgan-Stanley/binlog#74]
Currently its pretty ugly to use "{null}" to represent a nullptr for [const] char*. (binlog/const_char_ptr_is_string.hpp).

It seems to me that an "optional of char array" is a better choice?

**Comment by fdrex** [comment]
my solution (const_char_ptr_is_string.hpp):

```
template <>
struct CustomSerializer<const char*>
{
  template <typename OutputStream>
  static void serialize(const char* str, OutputStream& ostream)
  {
    if (str == nullptr) {
      mserialize::serialize(std::uint8_t{0}, ostream);
    } else {
      mserialize::serialize(std::uint8_t{1}, ostream);
      mserialize::serialize(string_view(str), ostream);
    }
  }

  static std::size_t serialized_size(const char* str)
  {
    return str == nullptr ? sizeof(std::uint8_t) : sizeof(std::uint8_t) + mserialize::serialized_size(string_view(str));
  }
};

template <>
struct CustomTag<const char*> : detail::Tag<std::shared_ptr<string_view>>::type {};
```

similarly, char_ptr_is_string.hpp need also be updated

**Comment by erenon** [comment]
There's no single right answer on how to treat `const char*`.

 - The type indicates it is an optional const character (not a string!)
 - C convention hints that it is a string
 - C standard printf doesn't allow the argument of `%s` to be `NULL`, but as an extension, glibc accepts it and prints `{null}`

Your solution mixes the type and convention hints, that's acceptable. However, it means that in the text output, `nullptr` and _empty string_ will have the same representation: a possible source of confusion.

There's no single right answer, and Binlog does not force any of that on you. Simply do not include the `binlog/binlog.hpp` convenience header, only the headers you use, and add your custom interpretation of `const char*`, just like in your example above.
