### ISSUE TITLE
Default SessionWriter id to unique value

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#76]
Users which use the default macros `BINLOG_INFO` etc. don't get any data printed for "Writer (thread) id" from bread and therefore are unable to distinguish log lines from different threads. This is because the SessionWriter constructor defaults id to 0. It would probably make sense for the default value to be `std::this_thread::get_id()` or similar?

**Comment by erenon** [comment]
Good point. See https://github.com/Morgan-Stanley/binlog/pull/77
