### ISSUE TITLE
Feature Request: Support collections with iterators of type std::input_iterator_tag

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#78]
As above, would it be possible to support collections with iterators of std::input_iterator_tag instead of requiring std::forward_iterator_tag?

It would mean it's not possible to know the size of the collection beforehand and an alternative way of encoding (removing the explicit serializing of the number of elements?) would be required. This might be useful in the generic case as well so as to avoid iterating through collections twice.

**Comment by erenon** [comment]
Supporting direct logging of input sequences is not planned. What's the use-case of consuming an input sequence purely for logging? FTR, the obvious workaround is copying the input sequence into a supported container first:

```
void log_input_sequence(InputSequence<T>& is)
{
    const std::vector<T> v(is.begin(), is.end()); // the price is a memory copy
    BINLOG_INFO("{}", v);
}
```

The technical reason of not supporting input sequences is keeping the serialization and queue allocation logic simple. To support values of unknown size, it'd need:

 - a special case for `mserialize::serialized_size`, increases complexity and compilation times
 - a different kind of logic for `QueueWriter::beginWrite`, that allows tentative allocation of the complete remaining free capacity
 - a different kind of `QueueWriter::write`, that checks the remaining capacity for each write (runtime penalty), and resizes the queue on overflow (difficult in the concurrent setting) or allocates a new queue (complicates ownership)

It has been done before, it is ugly.

> removing the explicit serializing of the number of elements

How would then the deserializer know when to stop?

> This might be useful in the generic case as well so as to avoid iterating through collections twice.

The collection is not iterated twice, if it has `.size()`. Do you have large, frequently logged containers that doesn't have a known size?
