### ISSUE TITLE
Consider using Nifty Counter idiom for static & thread_local init/deinit

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#90]
https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Nifty_Counter

We've run into some issues with static initialization order when using binlog in conjunction with other static objects. I believe implementing the nifty counter idiom or similar for static and thead_local variables in default_session.hpp would alleviate these issues.

**Comment by erenon** [comment]
How would that work with the thread_local session writers? Can you tell me more about your issue? 
(BTW, the nifty counter requires a global variable, that would need a C++17 only inline global, to remain header only)

**Comment by andrewkcorcoran** [comment]
The below example may or may not invoke UB on your machine (it depends on what order the compiler decides to init the static Test and the static binlog::default_session). On my machine it triggers an ASAN error. I don't think there is any mechanism in binlog to work around this and allow users to log in their static class destructors.

 

```cpp

#include "binlog/binlog.hpp"

struct Test
{
  ~Test()
    {
        BINLOG_INFO("Will invoke UB if static binlog::default_session has already been destroyed");
    }
};

auto & GetStaticClass()
{
    static auto test = Test{};
    return test;
}

int main()
{
    auto test = GetStaticClass();
}

**Comment by erenon** [comment]
How common is logging in static destructors in your codebase? What about this workaround?

```
#include "binlog/binlog.hpp"

struct Test
{
  Test(binlog::Session&) {}

  ~Test()
    {
        BINLOG_INFO("Will invoke UB if static binlog::default_session has already been destroyed");
    }
};

auto & GetStaticClass()
{
    static auto test = Test(binlog::default_session()); // invoking default_session() here ensures session is created sooner, therefore destructed sooner
    return test;
}

int main()
{
    auto test = GetStaticClass();
}
```

**Comment by andrewkcorcoran** [comment]
Yea I think that will work. I think it's acceptable to mark this as won't fix in binlog but if so it would probably be a good idea to add something to the wiki/readme regarding usage of the logger from static classes.

**Comment by erenon** [comment]
https://github.com/Morgan-Stanley/binlog/issues/91

**Comment by erenon** [comment]
Probably passing in the SessionWriter is even better:

```cpp
#include "binlog/binlog.hpp"

struct Test
{
  Test(binlog::SessionWriter&) {}

  ~Test()
    {
        BINLOG_INFO("Will invoke UB if static binlog::default_session has already been destroyed");
    }
};

auto & GetStaticClass()
{
    static auto test = Test(binlog::default_thread_local_writer());
    return test;
}

int main()
{
    auto test = GetStaticClass();
}
```
