### ISSUE TITLE
getchar() or getline will be blocked in binlog

### ISSUE THREAD

**Issue by kuibing126** [Morgan-Stanley/binlog#97]
Hey, 

 When there is getchar/std::getline(std::cin) function in my main() program, binlog will not work.
Does these two functions will hang up binlog event?

**Comment by kuibing126** [comment]
#include <binlog/binlog.hpp>
#include <iostream>
#include <fstream>

int main(int argc, char* argv[])
{
	BINLOG_INFO("Hello {}!", "World");

	std::ofstream logfile("hello.blog", std::ofstream::out | std::ofstream::binary);
	binlog::consume(logfile);

       string inputs;
        std::getline(std::cin, inputs);
        getchar();
    

}

**Comment by erenon** [comment]
hi, call `binlog::consume(logfile);` at the end of your program. detailed doc here: http://binlog.org/UserGuide.html#consume-logs

**Comment by kuibing126** [comment]
Thanks you.

If do so, hello.blog will not have any logs&nbsp;until my program&nbsp;quit. right?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Morgan-Stanley/binlog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午4:42
收件人:&nbsp;"Morgan-Stanley/binlog"<binlog@noreply.github.com&gt;;
抄送:&nbsp;"Bing"<7862483@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Morgan-Stanley/binlog] getchar() or getline will be blocked in binlog (#97)





 
hi, call binlog::consume(logfile); at the end of your program. detailed doc here: http://binlog.org/UserGuide.html#consume-logs

**Comment by kuibing126** [comment]
`
std::ofstream logfile("hello.blog", std::ofstream::out | std::ofstream::binary);
int main()
{
BINLOG_INFO("Hello {}!", "World");

	AppAdmin::ConsoleAdmin::Instance().Init(&io, std::bind(&AppAdmin::AdminCommand, &AppAdmin::ConsoleAdmin::Instance(), std::placeholders::_1));
	AppAdmin::SignalHandler signalHandler(io);
	std::thread t([&signalHandler]()
		{
			signalHandler.HandleInput();
		});

	t.join();

getchar()
	binlog::consume(logfile);
`


`
void SignalHandler::HandleInput()
{
	binlog::Session session;
	const std::size_t queueCapacityBytes = 1 << 20;
	binlog::SessionWriter writer(session, queueCapacityBytes);

	std::string buf;

	while (std::getline(std::cin, buf))
	{
		ConsoleAdmin::Instance().Command(buf);
		if (buf == "q")
		{
			return;
		}
		session.consume(logfile);
	}
}`


In this case, hello.blog has no any logs until the main program quit when I input "q".
But I don't wanna quit program to print log, How can I do that?

**Comment by erenon** [comment]
Please provide a MRE: https://stackoverflow.com/help/minimal-reproducible-example
If you are in doubt, add `printf` calls next to the `session.consume` calls, to make sure consume is called when needed.
In the code above, both `binlog::consume` and `session.consume` are used. This is allowed, but probably not what you want. Remove this part:

```
	binlog::Session session;
	const std::size_t queueCapacityBytes = 1 << 20;
	binlog::SessionWriter writer(session, queueCapacityBytes);
``

And keep using `binlog::consume` until you figure it out.

**Comment by kuibing126** [comment]
`#include <binlog/binlog.hpp>

#include <fstream>
#include <iostream>
#include <string>


int main()
{
    std::ofstream logfile("consume.blog", std::ofstream::out | std::ofstream::binary);

    std::string input;
    while (std::getline(std::cin, input))
    {
        if (input == "q")
            break;
        binlog::consume(logfile);
    }
    //]

    if (!logfile)
    {
        std::cerr << "Failed to write consume.blog\n";
        return 1;
    }

    std::cout << "Binary log written to consume.blog\n";
    binlog::consume(logfile);
    return 0;
}`

Above are my MRE.  I have to type 'q' to quit program, then consume.blog will be logged. If I close application by click 'X', then no any logs.

**Comment by erenon** [comment]
There are no log statements in this example. What output did you expect?

**Comment by kuibing126** [comment]
what I expect is that it should be able to output logs when I use getline(std::cin, buf) without any inputs.


I want to output logs when I use while (getline(std::cin, bufs)) in real-time.


Is any method/workarounds to implement?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Morgan-Stanley/binlog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午2:26
收件人:&nbsp;"Morgan-Stanley/binlog"<binlog@noreply.github.com&gt;;
抄送:&nbsp;"Bing"<7862483@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Morgan-Stanley/binlog] getchar() or getline will be blocked in binlog (#97)





 
There are no log statements in this example. What output did you expect?

**Comment by erenon** [comment]
I suspect your stdlib buffers writes to the ofstream. Try flushing it after consume:

```
        printf("consume called\r\n");
        binlog::consume(logfile);
        logfile.flush();
```

**Comment by kuibing126** [comment]
Seemingly, I input twice , consume.blog has log statements.&nbsp; When I just type 'd', then still no logs in consume.blog.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Morgan-Stanley/binlog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午2:59
收件人:&nbsp;"Morgan-Stanley/binlog"<binlog@noreply.github.com&gt;;
抄送:&nbsp;"Bing"<7862483@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Morgan-Stanley/binlog] getchar() or getline will be blocked in binlog (#97)





 
I suspect your stdlib buffers writes to the ofstream. Try flushing it after consume:
         printf("consume called\r\n");         binlog::consume(logfile);         logfile.flush();

**Comment by kuibing126** [comment]
> I suspect your stdlib buffers writes to the ofstream. Try flushing it after consume:
> 
> ```
>         printf("consume called\r\n");
>         binlog::consume(logfile);
>         logfile.flush();
> ```

![image](https://user-images.githubusercontent.com/75358276/100975502-15eb7700-3579-11eb-8cd6-af6842cf91de.png)
Seemingly, it still does not work. consume.blog still has 0 size.

**Comment by kuibing126** [comment]
> > I suspect your stdlib buffers writes to the ofstream. Try flushing it after consume:
> > ```
> >         printf("consume called\r\n");
> >         binlog::consume(logfile);
> >         logfile.flush();
> > ```
> 
> ![image](https://user-images.githubusercontent.com/75358276/100975502-15eb7700-3579-11eb-8cd6-af6842cf91de.png)
> Seemingly, it still does not work. consume.blog still has 0 size.

Hi, do you have any suggestion to get it around? This issue now blocked me.
I really want to use binlog in my project。
Thank you

**Comment by erenon** [comment]
Hi, I tested your code on Linux, it works as intended. I don't have direct access to windows machines, but similar tests run in CI on windows, and work as intended. Here's a slightly modified example that prints the number of consumed bytes and flushes the file:

```
#include <binlog/binlog.hpp>

#include <fstream>
#include <iostream>

int main()
{
    std::ofstream logfile("consume.blog", std::ofstream::out | std::ofstream::binary);

    BINLOG_INFO("Hello {}!", "World");

    std::string input;
    while (std::getline(std::cin, input))
    {
        if (input == "q")
            break;

        binlog::Session::ConsumeResult cr = binlog::consume(logfile);
        logfile.flush();
        std::cout << "Consumed " << cr.bytesConsumed << " bytes" << std::endl;
    }

    if (!logfile)
    {
        std::cerr << "Failed to write consume.blog\n";
        return 1;
    }

    std::cout << "Binary log written to consume.blog\n";
    binlog::consume(logfile);
    return 0;
}
```
